apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: django-typomatic
  annotations:
    github.com/project-slug: MaxOpperman/django-typomatic
spec:
  type: other
  lifecycle: unknown
  owner: guests
